language: python
python:
  - "2.7"

install:
  - pip install .
  - pip install -r requirements.txt

services:
  - memcached

# build matrix
branches:
  only:
    - master

# tests
script: nosetests


