language: python
python:
  - "2.7"

install:
  - pip install .
  - pip install -r requirements.txt

services:
  - memcached

branches:
  only:
    - master

script: nosetests

notifications:
  email:
    recipients:
      - gliese.ray@gmail.com
      - kotaimen.c@gmail.com


