#Travis-ci config file

language: python

python:
  - "2.7"


before_install:
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo add-apt-repository -y ppa:mapnik/v2.2.0
  - sudo apt-get update
  - sudo apt-get install -qq libjpeg-dev libz-dev libtiff-dev libfreetype6-dev liblcms-dev libwebp-dev libopenjpeg-dev
  - sudo pip install pillow
  - sudo apt-get install -qq gcc g++ gfortran libblas-dev liblapack-dev
  - sudo pip install numpy
  - sudo pip install scipy
  - sudo apt-get install -qq libgeos-dev libgdal-dev gdal-bin python-gdal
  - sudo apt-get install mapnik
  - geos-config --version
  - ogrinfo --version
#  - ogrinfo --formats
  - mapnik-config --version

install:
  - pip install .
  - pip install -r requirements.txt

services:
  - memcached

branches:
  only:
    - master

script:
  - nosetests

notifications:
  email:
    recipients:
      - gliese.q@gmail.com
      - kotaimen.c@gmail.com


